[workspace]
members = ["projects/*"]
default-members = [
    "projects/ie-windows",
    "projects/ie-runtime",
    "projects/ie-cli",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
